(define (square x) (* x x))
(define (make-from-real-imag x y)
  (define (dispatch op)
    (cond ((eq? op 'real-part) x)
          ((eq? op 'imag-part) y)
          ((eq? op 'magnitude)
           (sqrt (+ (square x) (square y))))
          ((eq? op 'angle) (atan y x))
          (else
           (error "Unknown op" op))))
  dispatch)

(define (apply-generic op arg) (arg op))
(define z (make-from-real-imag 2 3))
(z 'real-part)
(z 'imag-part)
(z 'magnitude)
(z 'angle)
(z 'unknwon)
