(define (square x) (* x x))
(define (make-from-mag-ang r a)
  (define (dispatch op)
    (cond ((eq? op 'real-part)
           (* r (cos a)))
          ((eq? op 'imag-part)
           (* r (sin a)))
          ((eq? op 'magnitude) r)
          ((eq? op 'angle) a)
          (else
           (error "Unknown op" op))))
  dispatch)

(define (apply-generic op arg) (arg op))
(define z (make-from-mag-ang 2 3))
(z 'real-part)
(z 'imag-part)
(z 'magnitude)
(z 'angle)
